### ISSUE TITLE
Backup-Force not starting the hook.global.after

### ISSUE THREAD

**Issue by fwischer** [neowit/backup-force.com#1]
Hello,

I've installed your programm onto a Debian GNU/Linux 8.9 (jessie). The Programm works fine and gets the backup Data onto the mounted Filesystem.
But the hook.global.after does not start with my script to gzip/move and delete the old .csv files.

Thanks for the help.

The log says the following (maybe it helps you):

Exception in thread "main" java.lang.NullPointerException
	at com.neowit.apex.backup.BackupSObject.com$neowit$apex$backup$BackupSObject$$runOneMode$1(BackupSObject.scala:148)
	at com.neowit.apex.backup.BackupSObject.run(BackupSObject.scala:170)
	at com.neowit.apex.backup.BackupRunner$$anonfun$com$neowit$apex$backup$BackupRunner$$runAllProcesses$1$1.apply(BackupRunner.scala:124)
	at com.neowit.apex.backup.BackupRunner$$anonfun$com$neowit$apex$backup$BackupRunner$$runAllProcesses$1$1.apply(BackupRunner.scala:122)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at com.neowit.apex.backup.BackupRunner$.com$neowit$apex$backup$BackupRunner$$runAllProcesses$1(BackupRunner.scala:122)
	at com.neowit.apex.backup.BackupRunner$$anonfun$run$1.apply$mcV$sp(BackupRunner.scala:148)
	at com.neowit.apex.backup.BackupRunner$$anonfun$run$1.apply(BackupRunner.scala:148)
	at com.neowit.apex.backup.BackupRunner$$anonfun$run$1.apply(BackupRunner.scala:148)
	at com.neowit.apex.backup.Benchmark$.apply(Benchmark.scala:28)
	at com.neowit.apex.backup.BackupRunner$.run(BackupRunner.scala:147)
	at com.neowit.apex.backup.BackupRunner$.main(BackupRunner.scala:46)
	at com.neowit.apex.backup.BackupRunner.main(BackupRunner.scala)

(its the end of our logfile)

**Comment by neowit** [comment]
Hello @fwischer 

Can you share your config file ? (with login/pass removed)

This error (based on the exception you included) looks like a connection problem at first glance.
Does backup work for you when `hook.global.after` is removed from configuration ?

If config without global hook works then can you try replacing your hook script content with something basic, like: 
```bash
#!/bin/bash
echo "$*"
```
just to eliminate the possibility that something is wrong with the script

**Comment by fwischer** [comment]
The Part with the Backup works fine.
It's just that it does not execute the Script after it is finished.

# backup-force.com configuration file
# see example of all possible properties at:
# https://github.com/neowit/backup-force.com/blob/master/config/sample-configuration.properties
# Fri Oct 13 16:18:02 CEST 2017
backup.objects=*
sf.username=email@mymail.com
outputFolder=/mnt/lol/dumps/
sf.serverurl=https\://xxxx.my.salesforce.com/
sf.password=MySuperSecretPW\Token
hook.global.after=/home/ganondorf/bin/sad.sh

This is the config we are currently using.

Thanks for your reply
Flo

**Comment by neowit** [comment]
Is sad.sh file executable ? I.e. does it have executable flag `+x` set ?
Have you tried replacing  sad.sh with a minimal content as I suggested above?
```sh
#!/bin/bash
echo "$*"
```

**Comment by fwischer** [comment]
Hello,

I replaced the script and tried again (i changed backup.objects=Account) so it will run a little bit faster.

```11:13:17.223 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Auth EndPoint: https://xxx.my.salesforce.com//services/Soap/u/28.0
11:13:17.229 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Service EndPoint: https://loyaltysystems.my.salesforce.com/services/Soap/u/28.0/00D24000000Ij3P
11:13:17.230 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Username: xxx
11:13:18.074 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: Trying mode: SyncWithoutGlobalWhere
11:13:51.226 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: 10866 lines
11:13:51.231 [main] DEBUG com.neowit.apex.backup.Benchmark$ - # Block "useBulkApi = false" completed, time taken: 33988 ms (33.988 s)```

Greetz
Flo

**Comment by neowit** [comment]
can you try [this version](https://www.dropbox.com/s/szm5u55ge7hrz18/backup-force.com-0.3.8-SNAPSHOT-jar-with-dependencies.jar?dl=1) please.
I have added some debugging around external script/hook execution, perhaps this will produce some more information

**Comment by fwischer** [comment]
```java -jar /root/backup-force.com-0.3.8-SNAPSHOT-jar-with-dependencies.jar --config /home/ganondorf/myconf.properties
12:22:56.555 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Auth EndPoint: https://xxx.my.salesforce.com//services/Soap/u/28.0
12:22:56.561 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Service EndPoint: https://loyaltysystems.my.salesforce.com/services/Soap/u/28.0/00D24000000Ij3P
12:22:56.561 [main] INFO  com.neowit.apex.backup.BackupRunner$ - Username: xxxx
12:22:57.241 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: Trying mode: SyncWithoutGlobalWhere
12:23:30.245 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: 10866 lines
12:23:30.248 [main] DEBUG com.neowit.apex.backup.Benchmark$ - # Block "useBulkApi = false" completed, time taken: 33671 ms (33.671 s)```

produced the same output as before

**Comment by neowit** [comment]
Interesting...
Have added some more debug output to [this version](https://www.dropbox.com/s/my77pyyn4lulmqf/backup-force.com-0.3.8.1-SNAPSHOT-jar-with-dependencies.jar?dl=1). Please try it and post output back here.
Thanks.

**Comment by fwischer** [comment]
```15:21:39.138 [main] DEBUG com.neowit.apex.backup.Config - execute hook: global.before
15:21:39.139 [main] DEBUG com.neowit.apex.backup.Config - scriptPath: 'None'
15:21:42.330 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: Trying mode: SyncWithoutGlobalWhere
15:21:43.712 [main] DEBUG com.neowit.apex.backup.Config - execute hook: each.before
15:21:43.713 [main] DEBUG com.neowit.apex.backup.Config - scriptPath: 'None'
15:22:14.784 [main] DEBUG com.neowit.apex.backup.Config - execute hook: each.after
15:22:14.784 [main] DEBUG com.neowit.apex.backup.Config - scriptPath: 'None'
15:22:14.784 [main] INFO  com.neowit.apex.backup.BackupSObject - Account: 10866 lines
15:22:14.786 [main] DEBUG com.neowit.apex.backup.BackupRunner$ - about to execute HookGlobalAfter. allSobjectSet=Account
15:22:14.787 [main] DEBUG com.neowit.apex.backup.Config - execute hook: global.after
15:22:14.788 [main] DEBUG com.neowit.apex.backup.Config - scriptPath: 'Some(/home/ganondorf/bin/sad.sh)'
15:22:14.788 [main] DEBUG com.neowit.apex.backup.Config - About to execute script: /home/ganondorf/bin/sad.sh /mnt/lol/dumps/
/mnt/lol/dumps/
15:22:14.841 [main] DEBUG com.neowit.apex.backup.Config - /home/ganondorf/bin/sad.sh was executed with exit code: 0
15:22:14.841 [main] DEBUG com.neowit.apex.backup.Benchmark$ - # Block "useBulkApi = false" completed, time taken: 35705 ms (35.705 s)```

the script that is executed.
```#!/usr/bin/env bash
# Florian Wischer
# 20.10.2017
echo "$*"```

**Comment by neowit** [comment]
As far as I can see from the log above your script was executed successfully
```
...
1: 15:22:14.788 [main] DEBUG com.neowit.apex.backup.Config - About to execute script: /home/ganondorf/bin/sad.sh /mnt/lol/dumps/
2: /mnt/lol/dumps/
3: 15:22:14.841 [main] DEBUG com.neowit.apex.backup.Config - /home/ganondorf/bin/sad.sh was executed with exit code: 0
```
output in line 2 above `/mnt/lol/dumps/` comes from `echo "$*"`

**Comment by fwischer** [comment]
```15:43:43.691 [main] DEBUG com.neowit.apex.backup.Config - execute hook: global.after
15:43:43.692 [main] DEBUG com.neowit.apex.backup.Config - scriptPath: 'Some(/home/ganondorf/bin/sfbk.sh)'
15:43:43.692 [main] DEBUG com.neowit.apex.backup.Config - About to execute script: /home/ganondorf/bin/sfbk.sh /mnt/lol/dumps/
2017-11-08: start backupforce...
2017-11-08: backupforce finished.
2017-11-08: start compressing...
2017-11-08: compressing finished.
2017-11-08: start removing csv files...
2017-11-08: removing csv files finished.
15:43:44.562 [main] DEBUG com.neowit.apex.backup.Config - /home/ganondorf/bin/sfbk.sh was executed with exit code: 0
15:43:44.562 [main] DEBUG com.neowit.apex.backup.Benchmark$ - # Block "useBulkApi = false" completed, time taken: 38763 ms (38.763 s)```

Thanks it now works even with the script that we intentionally wanted to run after its finished ... i have no Idea why it did not work when i used the 'older' version.
Thank you for your time and effort

Greetz
Flo
